spring:
  datasource:
    url: jdbc:mysql://localhost:3306/farm-data
    username: dev
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB